### ISSUE TITLE
Invalid entity

### ISSUE THREAD

**Issue by edememinov** [C0ntroller/discord-card#1]
When adding the following configuration to the lovelace card I get the error that the entity is invalid.

```
type: custom:discord-card
entity: sensor.discordusername_1234
```

![image](https://user-images.githubusercontent.com/7499362/134565590-c28fa77e-6054-443c-b594-f78f84e2ae82.png)

I am using your fork of [discord_game](https://github.com/C0ntroller/discord_game).

Any idea what I am doing wrong?

**Comment by C0ntroller** [comment]
This repository ist fairly out of date. I will add an hint to the Readme.

Currently I don't know if I will update it in the future.
